name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gradle-build:
    name: Gradle build (Java 8)
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: write
    env:
      BASE_PATH: ${{ github.workspace }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '8'
          cache: gradle

      - name: Make gradlew executable (Linux runner)
        run: chmod +x gradlew

      - name: Build all targets
        run: ./gradlew --no-daemon --stacktrace buildForgeAll

      - name: Upload JAR artifacts
        uses: actions/upload-artifact@v4
        with:
          name: IVV-all
          path: |
            out/*.jar
          if-no-files-found: error

      - name: Upload 1.12.2 JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: IVV-1.12.2
          path: |
            out/*1.12.2*.jar
          if-no-files-found: warn

      - name: Upload 1.16.5 JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: IVV-1.16.5
          path: |
            out/*1.16.5*.jar
          if-no-files-found: warn

      - name: Create GitHub Release (on tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          name: Immersive Vehicles Vanity ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            out/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}